image: golang:latest

variables:
  REPO_NAME: github.com/CharlesCatta/torrent-flixy

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME/server/

stages:
  - test

format:
  stage: test
  script:
    - go fmt $(go list ./.. | grep -v /vendor/)
    - go vet $(go list ./.. | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)